export const DefaultTraining = '/static/images/aim/course.jpg'
export const ExamenNoDisponible = '/static/images/aim/mantenimientoexam.jpg'
export const MedallaProgreso = '/static/images/aim/medalla.png'
export const Legend1 = '/static/images/aim/LegendReservas.png'
export const Legend2 = '/static/images/aim/LegendClases.png'